name: Install Helm Chart

inputs:
  chart_name:
    required: true
    type: string
    description: Helm Chart name
  repository_name:
    required: true
    type: string
    description: Helm Chart repository
  repository_ref:
    required: true
    type: string
    description: Helm Chart repository ref (tag or branch)
  repository_path:
    required: true
    type: string
    default: ""
    description: Helm Chart path in the repository
  cluster_name:
    required: true
    type: string
    description: Cluster name
  namespace:
    required: true
    type: string
    description: Namespace
  release_name:
    required: true
    type: string
    default: ""
    description: Release Name
  use_default_values:
    required: false
    type: boolean
    description: Use values.yaml
  default_values_file:
    required: true
    type: string
    default: values.yml
    description: the name of the default vaues file
  additional_values:
    required: false
    type: string
    default: ""
    description: Additional values files list separated by space
  additional_args:
    required: false
    type: string
    default: ""
    description: Additional arguments
  role-to-assume:
    required: true
    type: string
  aws-region:
    required: true
    type: string
  pat:
    required: true
    type: string

runs:
  using: composite
  steps:
      - name: Get Helm chart
        uses: actions/checkout@v4.1.1
        with:
            repository: ${{ inputs.repository_name }}
            path: "helm"
            token: ${{ inputs.pat }}
            ref: ${{ inputs.repository_ref }}
            sparse-checkout: ${{ inputs.repository_path }}
            sparse-checkout-cone-mode: false

      - name: Set up Helm
        uses: azure/setup-helm@v4.2.0
        with:
            version: v3.8.1

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
            role-to-assume: ${{ inputs.role-to-assume }}
            role-session-name: "github-actions-runner"
            aws-region: ${{ inputs.aws-region }}
            role-skip-session-tagging: true

      - name: Update kubeconfig
        shell: bash
        run: aws eks update-kubeconfig --name ${{inputs.cluster_name}} --region ${{inputs.aws-region}}

      - name: Upgrade helm chart
        shell: bash
        run: |
            set -x
            if [[ "${{ inputs.repository_path }}" == "" ]]; then
              cd helm
            else
              cd helm/${{ inputs.repository_path }}
            fi
            ARGS=$(
                if [[ "${{ inputs.use_default_values }}" == "true" ]]; then
                    echo " -f ${{ inputs.default_values_file }} ${{ inputs.additional_values }}"
                else
                    echo "${{ inputs.additional_values }}"
                fi
            )

            RELEASE_NAME=$(if [[ "${{inputs.release_name}}" == "" ]]; then echo ${{inputs.chart_name}}; else echo ${{inputs.release_name}};fi)

            helm upgrade --install \
                -n ${{inputs.namespace}} \
                ${RELEASE_NAME} \
                --create-namespace ${ARGS} . ${{ inputs.additional_args }}

